### PR TITLE
Android: add the titleId to the game card.

### PR DESCRIPTION
**Pull request by kongfl888**
Compared to game companies, users may be more interested in knowing what the title ID of this game is, 
as it can help them find game saves and the cheat file. 

In fact, many people have been troubled by not being able to find a game save location because they don't know what title ID is.

This PR will directly display the title ID in the game card, making it easier for users to find this ID. It replaced the game company.

old:
Screenshot_20240806_093212_old

new:
Screenshot_20240806_112050_new

### CODE REVIEW

**Comment by PabloMK7** [comment]
Hmmm I'm not sure about this change, can't we just display it below the game name?

**Comment by kongfl888** [comment]
> Hmmm I'm not sure about this change, can't we just display it below the game name?



Now it's like this

Screenshot_20240815_090235_org citra citra_emu

**Comment by kongfl888** [comment]
Preview



https://github.com/user-attachments/assets/24621bee-bdfa-41e9-856e-a26886744e0f

**Comment by PabloMK7** [comment]
Neat! Could you switch the company and the title ID, so that the company is at the top? Otherwise lgtm

**Review by PabloMK7 — APPROVED** [review]

**Review by PabloMK7 — APPROVED** [review]

**Pull request merged**
