### PR TITLE
Use archived version of gamedb (Nov 11 2023)

### PR DESCRIPTION
**Pull request by rtiangha**
Better than nothing? At least until a newer copy of the compatibility list can be found/made.

### CODE REVIEW

**Comment by PabloMK7** [comment]
Downloading from web archive may be very slow, since the file won't change it's better to just have it locally.

**Comment by rtiangha** [comment]
Well, I put a local copy in there just in case; could just remove the wget command for now. I wonder if gamedb was archived anywhere else. Or if there's a way to extract it from the most recent executable?

**Comment by DaniElectra** [comment]
If you have built citra from scratch, you should have a local copy of the compatibility list under `/path/to/build/dist/compatibility_list/compatibility_list.json`. Note that this only applies if you have remade the build directory recently.

I have a version from February 20th 2024, so I can submit it if you don't have a newer version

**Comment by rtiangha** [comment]
> If you have built citra from scratch, you should have a local copy of the compatibility list under `/path/to/build/dist/compatibility_list/compatibility_list.json`. Note that the list is only updated when you remake the build directory I think.
> 
> I have a version from February 20th 2024, so I can submit it if you don't have a newer version

Building from scratch after the shutdown doesn't pull anything because api.citra-emu.org is down so when I started playing around with the code a few days ago, my builds had no compatibility list.

Anyway, I would happily take a copy! And I reverted things so it no longer checks the Wayback Machine but keeps the file that's already there.

**Comment by DaniElectra** [comment]
> Building from scratch after the shutdown doesn't pull anything

That is right, I meant if you had build citra from sratch *before* the shutdown

Here is a copy I have of `compatibility_list.json` from February 21st 2024:
[compatibility_list.json](https://github.com/PabloMK7/citra/files/14547419/compatibility_list.json)

BTW, I think it would be better to modify the CMake files instead of `.ci/source.sh` so that the compatibility list can be toggled. And I think the PR currently doesn't do anything anyway?

**Comment by rtiangha** [comment]
@DaniElectra Thanks! Looks like your file and mine are exactly the same so I guess gamedb hasn't had any new updates in a while.

And yeah, all this PR does now is add a local copy of the file to where it's expected to be. Feel free to merge or close.

**Pull request closed without merging**
