### PR TITLE
Incorporate changes from Canary 2798

### PR DESCRIPTION
**Pull request by rtiangha**
Incorporate the last five PRs from canary:

Pull Request | Commit | Title | Author | Merged?
-- | -- | -- | -- | --
7372 | 265ed7e | pica_types: Correctly restrict Float<M, E> precision | vitor-k | Yes
7384 | 20ef8e4 | host_shaders: Remove dependency on shaderSampledImageArrayDynamicIndexing | GPUCode | Yes
7420 | 1d2f9bc | 3dsx: Minor cleanups and add argument support | GPUCode | Yes
7429 | 2fe2dd1 | renderer_vulkan: Rewrite descriptor set management and various small fixes | GPUCode | Yes
7472 | 2855c54 | y2r: Delay completion event | GPUCode | Yes

### CODE REVIEW

**Comment by PabloMK7** [comment]
@GPUCode has shown intentions to continue development, and it would be better to have the commits separated and from the original authors.

**Comment by GPUCode** [comment]
Yes these will need separate PRs. Aside from the descriptor one should be safe to merge. That needs more testing on android because its a large refactor

**Comment by Miguel-hrvs** [comment]
I'll be testing the descriptor one on android to compare stability

**Comment by Miguel-hrvs** [comment]
Guys bad news, with the four changes there's a regression on the black haired guy from pokemon x:

with canary changes:
https://github.com/PabloMK7/citra/assets/81558772/af03aa60-d2fa-4f04-b885-0470042547c1

without canary changes:
https://github.com/PabloMK7/citra/assets/81558772/b8428d79-c5c2-4253-bd91-8bbf787ca510

The disk cached shaders seem to work better without the canary changes. I'll test without the descriptor rewrite.

**Comment by GPUCode** [comment]
I can't see the regression on the videos, could you describe what the difference is?

**Comment by Miguel-hrvs** [comment]
In the first video there's a black point moving around the middle of his head

**Comment by Miguel-hrvs** [comment]
Now I tested without the descriptor one and the hair issue doesn't appear and the cached disk shaders now work great too. So it's save to merge all without the descriptor changes.

**Comment by Miguel-hrvs** [comment]
The pica sw_rasterizer.cpp from canary is giving me a compilation issue with gcc. I'll look into that.

**Comment by Miguel-hrvs** [comment]
Now I merged the pica things properly in my fork. Testing the vulkan canary commits without the descriptor changes.

**Comment by Miguel-hrvs** [comment]
Now I found out that the descriptor changes wasn't the problem with the regression, the bug is in other change from the canary commits. I'll see if I can find the exact file responsible.

**Comment by Miguel-hrvs** [comment]
I think that the regression came with this commit: https://github.com/PabloMK7/citra/pull/27/commits/4a63fc2ca2e47f08532fb44e23a4857fc4339d07#diff-c755cbd9e82145258a5530955eed815ae606c824d83bda79da02faffb9b3512a

I'll continue testing.

**Comment by Miguel-hrvs** [comment]
Without https://github.com/PabloMK7/citra/commit/d2af98673a636d9b86ea288e676a3e9b72c8eee5 
Everything seems to work great, even the descriptor changes.

**Comment by GPUCode** [comment]
How is the performance on android with the descriptor changed compared to nightly?

**Comment by Miguel-hrvs** [comment]
Compared to the nightly build, these changes work better in my npad s tablet.

**Comment by GPUCode** [comment]
How much is "better"?

**Comment by Miguel-hrvs** [comment]
slightly better in heavy gpu workloads on pokemon moon

**Comment by Miguel-hrvs** [comment]
These changes seem to solve this issue: https://github.com/PabloMK7/citra/issues/38

**Pull request closed without merging**
