### PR TITLE
renderer_vulkan: Rewrite descriptor set management and various small fixes

### PR DESCRIPTION
**Pull request by rtiangha**
The behaviour described in #38 happened in the final Citra Nightly (and here too) but not in the final Canary. This was the set of commits that fixes things. Might fix some other lingering Vulkan issues too.

### CODE REVIEW

**Comment by Miguel-hrvs** [comment]
GPUCode made a cleanup in renderer_vulkan.cpp scheduler.Record that could be good to test: https://github.com/raphaelthegreat/citra/commit/3a69f96d390aede2c998590c859cba6b401bee17

**Comment by rtiangha** [comment]
Is it a matter of reverting [3c74783](https://github.com/PabloMK7/citra/pull/77/commits/3c747831486f29c2e24adef7c0edbb06af3d3516) and adding the new one? Because I think that some of [00370bf](https://github.com/PabloMK7/citra/pull/77/commits/00370bf582f4a7134ccf8a8237c6643afebb4d5f) is dependent on the naming of the old patch, which means some of it might need to be ported? Unless there's a newer version of everything; I just used the older commits because that's what I was able to find.

**Comment by rtiangha** [comment]
Oh, I see; that commit was based off of the original Citra fork. Well, maybe I can just eyeball the changes and update the Pull Request since cherry-picking it directly is too hard and his citra-new fork is no longer around and I have no idea what's going on with the state of the scene right now.

**Comment by Miguel-hrvs** [comment]
Maybe it's better to leave the cleanup for a separate pr and let GPUCode explain those changes. Yep the scene is very unpredictable right now.

**Comment by rtiangha** [comment]
Nah, I think I can do this. It really is just a bit of a cleanup; the problem is that because it's based off of original Citra, cherry-picking the commit directly is trying to change this fork back to original Citra too and so there's lots of conflicts. Porting the changes won't be that hard.

**Comment by Miguel-hrvs** [comment]
Yep is better to pick manually in this case

**Comment by rtiangha** [comment]
Yeah, at the end of the day, the old patch changed the var name from `renderpass_cache` to `render_manager` while the new one used the old name. I recall running into this issue when trying to fix the telemetry stuff; my tree used the Canary name rather than the Nightly name, so when I was first working on it, it didn't merge in cleanly. So this time around, I'm choosing to go with the old name because I think with just changing the type rather than the name, it'll maintain compatibility with some of the other forks out there making cherry-picking easier since it won't break things as it seems most of the forks forked the Nightly branch rather than the Canary branch.

Anyway, just waiting to see if this thing will compile and run on a test branch, and if it does, I'll push it here.

**Comment by rtiangha** [comment]
And done.

**Comment by Miguel-hrvs** [comment]
yep, good idea maintaining the old name, it's better for compatibility as you said.

**Pull request merged**
