### PR TITLE
shader_jit/tests: Test both the shader interpreter and jit

### PR DESCRIPTION
**Pull request by Wunkolo**
Uses Catch2's `TEMPLATE_TEST_CASE`-feature to test both the JIT and the interpreter.

### CODE REVIEW

**Comment by Wunkolo** [comment]
Seems to expose a nested-loop bug in the shader-interpreter:
```
1: -------------------------------------------------------------------------------
1: Nested Loop - ShaderInterpreterTest
1: -------------------------------------------------------------------------------
1: /__w/citra/citra/src/tests/video_core/shader/shader_jit_compiler.cpp:636
1: ...............................................................................
1: 
1: /__w/citra/citra/src/tests/video_core/shader/shader_jit_compiler.cpp:669: FAILED:
1:   REQUIRE( shader_unit.address_registers[2] == expected_aL )
1: with expansion:
1:   0 == 5
```

**Comment by Wunkolo** [comment]
The issue seems to be an edge case here:
https://github.com/PabloMK7/citra/blob/e26ceabfd1d4f3d15063164f1a2d48cea5c138c0/src/video_core/shader/shader_interpreter.cpp#L709-L722

Multiple nested loops can be ending and incrementing at the same program counter. I'll look into a fix in another PR. This `if` should be a `for`/`while`-loop that checks all currently active loops and increments or ends each of them.

cc: @GPUCode

**Comment by Wunkolo** [comment]
ShaderInterpreter test is disabled for the Nested Loop test for now until the bug is fixed.

**Comment by Wunkolo** [comment]
Is there any additional work to be done on this before merging?

**Comment by PabloMK7** [comment]
I expected you wanted to fix the issue the test was detecting. I see now that you just disabled it.

**Comment by Wunkolo** [comment]
Scope of this PR is just to add the more-exhaustive testing without introducing a regressive test that we know will fail. Fixing that bug in particular is for another PR:
https://github.com/PabloMK7/citra/blob/b3f227e51c0ed1b801967d51513586f95aa34b91/src/tests/video_core/shader.cpp#L637-L639

**Pull request merged**
