### PR TITLE
Add "Steps per hour" system setting

### PR DESCRIPTION
**Pull request by szdarkhack**
This implements a "Steps per hour" system setting to be returned from `PTM:GetStepHistory`, as described in issue #208.

Currently the setting is global (i.e. not per-game).

### CODE REVIEW

**Comment by PabloMK7** [comment]
Can you send screenshot of the new UI? Also, would you be able to add the setting to android?

**Comment by szdarkhack** [comment]
The UI is shown below. I've tried my best to maintain the existing style and made sure it doesn't show in the per-game config. 

image

I don't think I'll be able to do the Android UI, at least not for now, but I can try it when I get some spare time again. Also I tried to make the setting work per-game but failed, I certainly intend to take another crack at that at some point (if noone beats me to it).

Any suggestions for improving the setting label or any such detail are of course welcome.

**Comment by szdarkhack** [comment]
Terribly sorry, I just realized I had the wrong author set and had to amend and force push. Nothing else has changed of course.

**Review by PabloMK7 — CHANGES_REQUESTED** [review]
Please make sure to edit the non-qt citra so that it loads the setting from the .ini file. Also edit the Android files so that it does the same (even if no UI exists).
Take a look at the config.cpp changes in https://github.com/PabloMK7/citra/pull/209

**Comment by szdarkhack** [comment]
I've made the requested changes and tested that the ini value is properly loaded (and works as intended) for both the SDL frontend and the android version.

**Review by PabloMK7 — APPROVED** [review]

**Pull request merged**
